#first create a folder - mkdir ~/docker-prometheus
#create a file - docker-compose.yml inside it with the following contents
#you also need to copy prometheus.yml file inside the same directory

version: '3.2'
services:
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - 9092:3000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    ports:
      - 9091:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis-monitoring
    ports:
      - 6379:6379
