#prometheus.yml - file
#this must be in the same directory as of docker-compose.yml file

scrape_configs:
- job_name: cadvisor
  scrape_interval: 10s
  static_configs:
  - targets:
    - cadvisor:9091
